name: streamZ
description: A simple video streaming application made with Dart, JS, HTML & CSS
version: 1.0.1
homepage: https://github.com/itzmeanjan/streamZ.git
author: Anjan Roy <anjanroy@yandex.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.7.0
